"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = ActivitiesScreen;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = require("react");
const AddActivityModal_1 = __importDefault(require("./components/AddActivityModal"));
const activitiesStore_1 = require("../state/activitiesStore");
function ActivitiesScreen() {
    const { activities, toggleActivity, deleteActivity } = (0, activitiesStore_1.useActivities)();
    const [showAdd, setShowAdd] = (0, react_1.useState)(false);
    const completedCount = (0, react_1.useMemo)(() => activities.filter((a) => a.completed).length, [activities]);
    const totalCount = activities.length;
    const remaining = Math.max(0, totalCount - completedCount);
    const progressPct = totalCount === 0 ? 0 : Math.round((completedCount / totalCount) * 100);
    return ((0, jsx_runtime_1.jsxs)("div", { className: "page", children: [(0, jsx_runtime_1.jsxs)("div", { className: "pageHeaderRow", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h1", { className: "pageTitle", children: "Daily Activities" }), (0, jsx_runtime_1.jsx)("p", { className: "pageSubtitle", children: "Track your daily routine and tasks" })] }), (0, jsx_runtime_1.jsx)("button", { className: "btn primary", onClick: () => setShowAdd(true), children: "+ Add Activity" })] }), (0, jsx_runtime_1.jsxs)("section", { className: "card", children: [(0, jsx_runtime_1.jsx)("div", { className: "cardHeader", children: (0, jsx_runtime_1.jsxs)("div", { className: "cardTitleRow", children: [(0, jsx_runtime_1.jsx)("span", { className: "cardIcon", "aria-hidden": "true", children: "\uD83D\uDCC5" }), (0, jsx_runtime_1.jsx)("h2", { className: "cardTitle", children: "Today's Progress" })] }) }), (0, jsx_runtime_1.jsxs)("div", { className: "progressWrap", "aria-label": "Activities completed progress", children: [(0, jsx_runtime_1.jsxs)("div", { className: "progressMeta", children: [(0, jsx_runtime_1.jsx)("span", { className: "muted", children: "Activities Completed" }), (0, jsx_runtime_1.jsxs)("strong", { className: "progressCount", children: [completedCount, " / ", totalCount] })] }), (0, jsx_runtime_1.jsx)("div", { className: "progressBar", role: "progressbar", "aria-valuenow": completedCount, "aria-valuemin": 0, "aria-valuemax": totalCount, "aria-valuetext": `${completedCount} of ${totalCount} completed`, children: (0, jsx_runtime_1.jsx)("div", { className: "progressFill", style: { width: `${progressPct}%` } }) }), (0, jsx_runtime_1.jsxs)("div", { className: "muted", children: [remaining, " activities remaining"] })] })] }), (0, jsx_runtime_1.jsxs)("section", { className: "card", children: [(0, jsx_runtime_1.jsxs)("div", { className: "cardHeader", children: [(0, jsx_runtime_1.jsx)("h2", { className: "cardTitle", children: "Today's Schedule" }), (0, jsx_runtime_1.jsx)("p", { className: "cardSubtitle", children: "Check off activities as you complete them throughout the day" })] }), (0, jsx_runtime_1.jsx)("ul", { className: "activityList", "aria-label": "Today schedule list", children: activities.map((a) => {
                            const rowClass = a.completed ? "activityRow done" : "activityRow";
                            return ((0, jsx_runtime_1.jsxs)("li", { className: rowClass, children: [(0, jsx_runtime_1.jsxs)("label", { className: "activityLeft", children: [(0, jsx_runtime_1.jsx)("input", { type: "checkbox", className: "bigCheckbox", checked: a.completed, onChange: () => toggleActivity(a.id), "aria-label": `Mark ${a.title} as ${a.completed ? "not completed" : "completed"}` }), (0, jsx_runtime_1.jsx)("span", { className: "activityTitle", children: a.title })] }), (0, jsx_runtime_1.jsxs)("div", { className: "activityRight", children: [a.time && ((0, jsx_runtime_1.jsxs)("span", { className: "activityTime", "aria-label": `Time ${a.time}`, children: ["\uD83D\uDD52 ", a.time] })), (0, jsx_runtime_1.jsx)("button", { className: "iconBtn danger", onClick: () => deleteActivity(a.id), "aria-label": `Delete ${a.title}`, title: "Delete", children: "\uD83D\uDDD1" })] })] }, a.id));
                        }) }), (0, jsx_runtime_1.jsxs)("div", { className: "tipsBox", children: [(0, jsx_runtime_1.jsxs)("div", { className: "tipsTitleRow", children: [(0, jsx_runtime_1.jsx)("span", { className: "tipsIcon", "aria-hidden": "true", children: "\u2705" }), (0, jsx_runtime_1.jsx)("strong", { children: "Daily Routine Tips" })] }), (0, jsx_runtime_1.jsxs)("ul", { className: "tipsList", children: [(0, jsx_runtime_1.jsx)("li", { children: "Stick to a consistent daily schedule when possible" }), (0, jsx_runtime_1.jsx)("li", { children: "Plan activities during your best times of day" }), (0, jsx_runtime_1.jsx)("li", { children: "Break larger tasks into smaller, manageable steps" }), (0, jsx_runtime_1.jsx)("li", { children: "Don't forget to schedule rest periods throughout the day" })] })] })] }), showAdd && (0, jsx_runtime_1.jsx)(AddActivityModal_1.default, { onClose: () => setShowAdd(false) })] }));
}
